-- Redcore core schema (spec §8).
-- gen_random_uuid() is built into PostgreSQL 13+.

create table organizations (
  id              uuid primary key default gen_random_uuid(),
  type            text not null check (type in ('family', 'emi', 'govt', 'enterprise')),
  name            text not null,
  region          text not null default 'IN',
  -- Telemetry retention window in days (spec §3.4). Phase 2 orgs collect no telemetry.
  retention_days  integer not null default 30 check (retention_days between 1 and 365),
  -- HMAC secret for the EMI payment webhook (spec §7). Null for non-EMI orgs.
  webhook_secret  text,
  created_at      timestamptz not null default now()
);

create table admins (
  id             uuid primary key default gen_random_uuid(),
  -- Null org_id is only valid for super_admin.
  org_id         uuid references organizations(id) on delete cascade,
  role           text not null check (role in ('super_admin', 'org_admin', 'operator', 'read_only')),
  email          text not null unique,
  display_name   text not null,
  password_hash  text not null,
  mfa_secret     text,
  mfa_enabled    boolean not null default false,
  disabled_at    timestamptz,
  created_at     timestamptz not null default now(),
  check (role = 'super_admin' or org_id is not null)
);

create table refresh_tokens (
  id          uuid primary key default gen_random_uuid(),
  admin_id    uuid not null references admins(id) on delete cascade,
  token_hash  text not null unique,
  expires_at  timestamptz not null,
  revoked_at  timestamptz,
  created_at  timestamptz not null default now()
);

-- A pairing code / QR generated by an admin (spec §4.1, §5.1). Carries the
-- consent attestation made by the admin; the device holder acknowledges it on
-- the device during enrollment.
create table enrollment_tokens (
  id                  uuid primary key default gen_random_uuid(),
  org_id              uuid not null references organizations(id) on delete cascade,
  created_by          uuid not null references admins(id),
  code                text not null unique,
  subject_label       text not null,
  owner_ref           text,
  management_mode     text not null check (management_mode in ('device_owner', 'profile_owner')),
  ownership           text not null check (ownership in ('byod', 'company')),
  consent_type        text not null check (consent_type in ('guardian_of_minor', 'company_owned')),
  subject_age         integer,
  attester_name       text not null,
  attestation_text    text not null,
  attestation_version text not null,
  doc_ref             text,
  policy_id           uuid,
  expires_at          timestamptz not null,
  used_at             timestamptz,
  device_id           uuid,
  created_at          timestamptz not null default now()
);

create table devices (
  id                 uuid primary key default gen_random_uuid(),
  org_id             uuid not null references organizations(id) on delete cascade,
  owner_ref          text,
  display_name       text not null,
  manufacturer       text,
  model              text,
  os_version         text,
  sdk_int            integer,
  agent_version      text,
  enroll_ts          timestamptz not null default now(),
  consent_id         uuid,
  ownership          text not null check (ownership in ('byod', 'company')),
  management_mode    text not null check (management_mode in ('device_owner', 'profile_owner')),
  fcm_token          text,
  credential_hash    text not null unique,
  status             text not null default 'active' check (status in ('active', 'retired')),
  last_seen          timestamptz,
  integrity_verdict  jsonb,
  desired_state      jsonb not null,
  desired_version    integer not null default 1,
  reported_state     jsonb,
  reported_version   integer not null default 0,
  created_at         timestamptz not null default now()
);
create index devices_org_idx on devices(org_id);

create table consents (
  id                     uuid primary key default gen_random_uuid(),
  org_id                 uuid not null references organizations(id) on delete cascade,
  device_id              uuid references devices(id) on delete cascade,
  type                   text not null check (type in ('guardian_of_minor', 'company_owned')),
  attested_by            uuid not null references admins(id),
  attester_name          text not null,
  subject_label          text not null,
  subject_age            integer,
  coppa_applicable       boolean not null default false,
  attestation_text       text not null,
  attestation_version    text not null,
  doc_ref                text,
  device_acknowledged_at timestamptz not null,
  device_holder_name     text,
  created_at             timestamptz not null default now()
);

alter table devices add constraint devices_consent_fk foreign key (consent_id) references consents(id);

create table policies (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references organizations(id) on delete cascade,
  name        text not null,
  phase       integer not null check (phase in (1, 2)),
  spec        jsonb not null,
  version     integer not null default 1,
  created_by  uuid references admins(id),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table enrollment_tokens add constraint enrollment_tokens_policy_fk
  foreign key (policy_id) references policies(id) on delete set null;

create table device_policy (
  device_id   uuid primary key references devices(id) on delete cascade,
  policy_id   uuid not null references policies(id) on delete cascade,
  applied_ts  timestamptz not null default now()
);

-- Durable, idempotent, acked command queue (spec §7).
create table commands (
  id               uuid primary key default gen_random_uuid(),
  org_id           uuid not null references organizations(id) on delete cascade,
  device_id        uuid not null references devices(id) on delete cascade,
  type             text not null,
  payload          jsonb not null,
  envelope         text not null,
  signature        text not null,
  status           text not null default 'pending'
                   check (status in ('pending', 'delivered', 'succeeded', 'failed', 'expired', 'cancelled')),
  -- Exactly one of issued_by / issued_by_system is set: every command is attributable.
  issued_by        uuid references admins(id),
  issued_by_system text,
  idempotency_key  text,
  attempts         integer not null default 0,
  next_attempt_at  timestamptz not null default now(),
  expires_at       timestamptz not null,
  delivered_at     timestamptz,
  ack_ts           timestamptz,
  result           jsonb,
  created_at       timestamptz not null default now(),
  check ((issued_by is null) <> (issued_by_system is null)),
  unique (device_id, idempotency_key)
);
create index commands_pending_idx on commands(device_id, status, next_attempt_at);

create table wallpapers (
  id            uuid primary key default gen_random_uuid(),
  org_id        uuid not null references organizations(id) on delete cascade,
  name          text not null,
  content_type  text not null,
  size_bytes    integer not null,
  sha256        text not null,
  storage_key   text not null,
  created_by    uuid references admins(id),
  created_at    timestamptz not null default now()
);

create table loans (
  id                   uuid primary key default gen_random_uuid(),
  org_id               uuid not null references organizations(id) on delete cascade,
  device_id            uuid not null unique references devices(id) on delete cascade,
  account_ref          text not null,
  currency             text not null default 'INR',
  reminder_days        integer not null default 3,
  grace_days           integer not null default 2,
  hard_lock_after_days integer not null default 7,
  support_contact      text not null,
  payment_url          text,
  auto_lock_paused     boolean not null default false,
  status               text not null default 'active' check (status in ('active', 'closed')),
  last_tier            text not null default 'ok',
  terms_disclosed_at   timestamptz not null,
  created_at           timestamptz not null default now(),
  unique (org_id, account_ref),
  check (grace_days >= 0 and hard_lock_after_days > grace_days)
);

create table loan_installments (
  id           uuid primary key default gen_random_uuid(),
  loan_id      uuid not null references loans(id) on delete cascade,
  seq          integer not null,
  due_date     date not null,
  amount       numeric(14, 2) not null check (amount > 0),
  paid_at      timestamptz,
  payment_ref  text,
  unique (loan_id, seq)
);

create table payments (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references organizations(id) on delete cascade,
  loan_id      uuid not null references loans(id) on delete cascade,
  payment_ref  text not null,
  amount       numeric(14, 2) not null,
  paid_at      timestamptz not null,
  raw          jsonb not null,
  created_at   timestamptz not null default now(),
  unique (org_id, payment_ref)
);

create table telemetry (
  id          bigserial primary key,
  org_id      uuid not null references organizations(id) on delete cascade,
  device_id   uuid not null references devices(id) on delete cascade,
  kind        text not null,
  payload     jsonb not null,
  ts          timestamptz not null,
  expires_at  timestamptz not null
);
create index telemetry_device_kind_idx on telemetry(device_id, kind, ts desc);
create index telemetry_expiry_idx on telemetry(expires_at);

create table alerts (
  id               uuid primary key default gen_random_uuid(),
  org_id           uuid not null references organizations(id) on delete cascade,
  device_id        uuid not null references devices(id) on delete cascade,
  kind             text not null,
  payload          jsonb not null default '{}',
  ts               timestamptz not null default now(),
  acknowledged_at  timestamptz,
  acknowledged_by  uuid references admins(id)
);
create index alerts_org_idx on alerts(org_id, ts desc);

create table audit_events (
  id           bigserial primary key,
  org_id       uuid references organizations(id) on delete cascade,
  actor_type   text not null check (actor_type in ('admin', 'device', 'system', 'webhook')),
  actor_id     text,
  action       text not null,
  target_type  text,
  target_id    text,
  meta         jsonb not null default '{}',
  ip           text,
  ts           timestamptz not null default now()
);
create index audit_org_ts_idx on audit_events(org_id, ts desc);
create index audit_target_idx on audit_events(target_type, target_id);
